### ISSUE TITLE
Task specified is invalid or does not exist

### ISSUE THREAD

**Issue by lordgogi** [openmodal/OpenModal#29]
After testing response the impact and response are shown but then the program freezes with following:
(win10, NIDAQ17 )

Can anyone help?

Thank you

Process Process-1:
Traceback (most recent call last):
  File "C:\Users\jgo\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\jgo\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\11_OpenModal\OpenModal-master\OpenModal\daqprocess.py", line 180, in __init__
    self.wait()
  File "D:\11_OpenModal\OpenModal-master\OpenModal\daqprocess.py", line 189, in wait
    self.measurement_triggered()
  File "D:\11_OpenModal\OpenModal-master\OpenModal\daqprocess.py", line 289, in measurement_triggered
    data = self.task.acquire_base()
  File "D:\11_OpenModal\OpenModal-master\OpenModal\DAQTask.py", line 146, in acquire_base
    None)
  File "<string>", line 3, in ReadAnalogF64
  File "<string>", line 2, in function
  File "C:\Users\jgo\AppData\Local\Programs\Python\Python36\lib\site-packages\PyDAQmx\DAQmxFunctions.py", line 29, in mafunction
    raise DAQError(error,errBuff.value.decode("utf-8"), f.__name__)
PyDAQmx.DAQmxFunctions.DAQError: Task specified is invalid or does not exist.
Status Code: -200088
 in function DAQmxReadAnalogF64

**Comment by jankoslavic** [comment]
@lordgogi please look at the error: "Task specified is invalid or does not exist".
Have you defined the task in MAX? checkout this video: https://youtu.be/YHupUB6bF6I?t=1m21s

**Comment by lordgogi** [comment]
Janko,

thank you. I indeed was wrong setup of the task (Acquisition mode was not set to be continuous.)
