### ISSUE TITLE
Error Qt QHeaderView

### ISSUE THREAD

**Issue by lordgogi** [openmodal/OpenModal#30]
Dear all,

if I try to execute in following virtual environment:

numpy (1.13.3)
pandas (0.19.1)
pip (9.0.1)
PyDAQmx (1.3.2)
PyOpenGL (3.1.0)
PyQt4 (4.11.4)
pyqtgraph (0.10.0)
python-dateutil (2.6.1)
pytz (2016.7)
pyuff (1.17)
QtAwesome (0.3.3)
QtPy (1.1.2)
setuptools (36.6.0)
six (1.10.0)
wheel (0.30.0)

I am getting this:

`(OpenModal2) D:\13_dev\OpenModal2\OpenModal-master\OpenModal>python openmodal.py
Traceback (most recent call last):
  File "openmodal.py", line 63, in <module>
    main_window = sk.FramelesContainer(app.desktop())
  File "D:\13_dev\OpenModal2\OpenModal-master\OpenModal\gui\skeleton.py", line 301, in __init__
    self.main_app = MainApp(desktop_widget, self.frameGeometry, self)
  File "D:\13_dev\OpenModal2\OpenModal-master\OpenModal\gui\skeleton.py", line 376, in __init__
    self.main_window = MainWindow(desktop_widget, frameGeometry, main_window_handle)
  File "D:\13_dev\OpenModal2\OpenModal-master\OpenModal\gui\skeleton.py", line 655, in __init__
    self._load_all_widgets()
  File "D:\13_dev\OpenModal2\OpenModal-master\OpenModal\gui\skeleton.py", line 707, in _load_all_widgets
    self.measurement_configuration_window = cf.ExcitationConfig(self.desktop_widget, self.preferences)
  File "..\OpenModal\gui\preferences_window.py", line 93, in __init__
    self.channel_table, self.channel_settings, self.preview_area = self.channels_widget()
  File "..\OpenModal\gui\preferences_window.py", line 517, in channels_widget
    header_view.setSectionResizeMode(0, header_view.Stretch)
AttributeError: 'QHeaderView' object has no attribute 'setSectionResizeMode'`

**If however I install following:**

QtAwesome (0.4.4)
QtPy (1.3.1)

the program runs but after hitting new model button I am getting this:

`Traceback (most recent call last):
  File "..\OpenModal\gui\widgets\geometry.py", line 1805, in new_model
    response,model_name=dialog_new_model.return_data()
  File "..\OpenModal\gui\widgets\geometry.py", line 2214, in return_data
    dialog = dialog_new_model(parent)
  File "..\OpenModal\gui\widgets\geometry.py", line 2187, in __init__
    src = Template(fh.read())
  File "C:\Users\jgo\Envs\OpenModal2\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 75: character maps to <undefined>`

Probably not bug but my ignoprance....can anyone help me please?

Thank You,
Jakub

**Comment by lordgogi** [comment]
Win10,
Python 3.6

**Comment by jankoslavic** [comment]
@lordgogi are you using the ubuntu-linux-tested version (this works also on win)
https://github.com/openmodal/OpenModal/tree/ubuntu-linux-tested

**Comment by lordgogi** [comment]
Janko,

I tried that version but I am getting

`(OpenModal2) D:\13_dev\OpenModal2\OpenModal-ubuntu-linux-tested\OpenModal>python openmodal.py
Traceback (most recent call last):
  File "openmodal.py", line 27, in <module>
    from PyQt5 import QtGui, QtWidgets, QtWebEngineWidgets
ModuleNotFoundError: No module named 'PyQt5'`


Shall I install Qt5?

**Comment by jankoslavic** [comment]
@lordgogi you should have installed pyqt5 (and not pyqt4 - which is the case for other branches of the program openmodal; I propose you to work in and python or conda environment)

**Comment by jankoslavic** [comment]
PS: you can pip install it (or use conda if you use anaconda)

**Comment by matmr** [comment]
pyqt5 is nice in that you can just pip-install it. This wasn't the case for pyqt4 (as far as I'm aware). As @jankoslavic suggested anaconda is way to go if you don't want to bother with package management.

You could also try
```
pip install -r requirements.txt
```
inside the openmodal folder. This will take care of all the required packages.
