### ISSUE TITLE
Openmodal crashes immediately after’ seting on”Create Geometry” window. Help wanted

### ISSUE THREAD

**Issue by 0800891** [openmodal/OpenModal#41]
I could open openmodal.py on OSX HighSiera.
However, when I tried to start project by setting geometry on “Create Geometry” window,
openmodal.py crashed.

It seems there is something wrong with panda on my computer.
I put messages on Terminal of OSX that shows all command lines.

——————————————-—————————————
mitsuh'shi-kous'ku-no-iM'c-2/OpenMod'l kous'kumitsuh'shi$ python openmod'l.py
W'rning: QApplic'tion w's cre'ted before pyqtgr'ph w's imported; there m'y be problems (to 'void bugs, c'll
QApplic'tion.setGr'phicsSystem("r'ster") before the QApplic'tion is cre'ted). Welcome upd'te time: 3.0994415283203125e-06 seconds
GVA info: Successfully connected to the Intel plugin, offline Gen9
Cle'ring previous models
Storing model id: 0
Geometry upd'te time: 0.01621413230895996 seconds
Exc type ch'nged
Me'surement upd'te time: 0.010705232620239258 seconds
Identific'tion upd'te time: 0.025530099868774414 seconds
Cle'ring previous models
Storing model id: 0
2D d't' not 'v'il'ble.
Anim'tion upd'te time: 0.03529810905456543 seconds
libpng w'rning: iCCP: known incorrect sRGB profile
libpng w'rning: iCCP: cHRM chunk does not m'tch sRGB
libpng w'rning: iCCP: known incorrect sRGB profile
libpng w'rning: iCCP: cHRM chunk does not m'tch sRGB
libpng w'rning: iCCP: known incorrect sRGB profile
libpng w'rning: iCCP: cHRM chunk does not m'tch sRGB
libpng w'rning: iCCP: known incorrect sRGB profile
libpng w'rning: iCCP: cHRM chunk does not m'tch sRGB
model 0.000000 'lre'dy stored - skipping
QL'yout: Attempting to 'dd QL'yout "" to di'log_geom_primitives "", which 'lre'dy h's ' l'yout
QWidget::setL'yout: Attempting to set QL'yout "" on di'log_geom_primitives "", which 'lre'dy h's ' l'yout
libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile
libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile libpng w'rning: iCCP: known incorrect sRGB profile Tr'ceb'ck (most recent c'll l'st):
File "../OpenMod'l/gui/widgets/geometry.py", line 921, in cre'te_geom_primitive self.cre'te_line_geom(input_d't')

File "../OpenMod'l/gui/widgets/geometry.py", line 965, in cre'te_line_geom node_m'sk=self.mod'ld't'.t'bles['geometry'].ix[:,'node_nums'].isin(node_nums)
File "/Users/kous'kumitsuh'shi/'n'cond'3/lib/python3.6/site-p'ck'ges/p'nd's/core/series.py", line 2555, in isin result = 'lgorithms.isin(_v'lues_from_object(self), v'lues)
File "/Users/kous'kumitsuh'shi/'n'cond'3/lib/python3.6/site-p'ck'ges/p'nd's/core/'lgorithms.py", line 426, in isin return f(comps, v'lues)
File "/Users/kous'kumitsuh'shi/'n'cond'3/lib/python3.6/site-p'ck'ges/p'nd's/core/'lgorithms.py", line 404, in <l'mbd'>
f = l'mbd' x, y: ht'ble.ismember_object(x, v'lues)
File "p'nd's/_libs/h'sht'ble_func_helper.pxi", line 428, in p'nd's._libs.h'sht'ble.ismember_object (p'nd's/_libs/
h'sht'ble.c:30162)
V'lueError: Buffer dtype mism'tch, expected 'Python object' but got 'double' Abort tr'p: 6

**Comment by miha-pirnat** [comment]
The application was not tested on OS X...I think the problem could lie in ''W'rning: QApplic'tion w's cre'ted before pyqtgr'ph w's imported; there m'y be problems (to 'void bugs, c'll
QApplic'tion.setGr'phicsSystem("r'ster") before the QApplic'tion is cre'ted).''

You are welcome to try to solve this and help improve OpenModal.

**Comment by 0800891** [comment]
Thank you for your reply, ‘miha-pirnat’.
So what should I do for next step to help improve OpemModal???

**Comment by miha-pirnat** [comment]
You can ''fork'' the source code and improve it, then create pull request to implement your code in our source. In this way your improvement helps everybody.

**Comment by 0800891** [comment]
I put the source code as following.
and for a next step, I should find the way how I can "call QApplication.setGraphhicsSystem before the QApplication is created.....
----------------Source Code of "openmodal.py"----------------------
# Copyright (C) 2014-2017 Matjaž Mršnik, Miha Pirnat, Janko Slavič, Blaž Starc (in alphabetic order)
# 
# This file is part of OpenModal.
# 
# OpenModal is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
# 
# OpenModal is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with OpenModal.  If not, see <http://www.gnu.org/licenses/>.

import sys, time, os

import multiprocessing as mp
#
# if __name__ == '__main__':
#     executable = os.path.join(os.path.dirname(sys.executable), 'openmodal.exe')
#     mp.set_executable(executable)
#     mp.freeze_support()

from PyQt5 import QtGui, QtWidgets, QtWebEngineWidgets

class Logger(object):
    def __init__(self, filename):
        self.terminal = sys.stderr
        self.log = open(filename, 'w')

    def write(self, message):
        self.terminal.write(message)
        self.log.write(message)

    def flush(self):
        self.terminal.flush()
        self.log.close()

if os.path.isdir('log'):
    pass
else:
    os.mkdir('log')

#sys.stderr = Logger('log/{0:.0f}_log.txt'.format(time.time()))

sys.path.append('../')

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    #TODO: do we need the following?
    #app.addLibraryPath('c:/Anaconda3/Lib/site-packages/PyQt5/plugins/')

    #pixmap = QtGui.QPixmap('gui/widgets/splash.png')
    #splash = QtGui.QSplashScreen(pixmap)
    #splash.show()

    #splash.showMessage('Importing modules ...')
    app.processEvents()
    import gui.skeleton as sk

    main_window = sk.FramelesContainer(app.desktop())
    #splash.showMessage('Building environment ...')
    app.processEvents()

    main_window.show()

    #splash.finish(main_window)

    #sys.exit(app.exec_())
    app.exec()

--------------source code end------------------------

**Comment by miha-pirnat** [comment]
You can try also this steps from @matjazzz @matmr 


```
We've had some report of successful installations on OSX, but not everything always worked.

I copy pasted below short instructions on installation under OSX, which should be very similar to Linux procedure. My advice is to do this inside a classic Python install (rather than anaconda etc.).

>>pip install virtualenv
This installs virtual environment package. It enables you to setup a 'sandbox' python. Very useful - definitely read up on it if you haven't yet.
>> python -m virtualenv openmodal-virtualenv
This creates the sandbox python inside a folder called openmodal-virtualenv. Now we need to activate this python. You have to find a script called 'activate' somewhere inside. On linux it's under bin/activate.
>>source bin/activate
Once you run it (you should check if you need to run with source command on mac), you will operate with this sandbox python. I hope that makes sense :) Next, we need to move to the folder where you have your downloaded distribution of openmodal. It should be 'ubuntu-linux-tested' branch.
>>git clone https://github.com/openmodal/OpenModal.git
>>cd OpenModal
>> git checkout ubuntu-linux-tested
Now that we have the specific branch, we can load all the python packages with one command.
>>pip -install -r requirements.txt
Python packages needed for openmodal will be installed. And the final step is to run the software.
>>cd OpenModal
>>python openmodal.py
```

**Comment by 0800891** [comment]
Thank you for your information.
Although I have Anaconda installed in my computer,  i tried "matjazz"'s instruction on "terminal.app".
So i think I did "inside a classic Python install (rather than anaconda etc.)".
However it seams that I got same result as the one I have before.
(Maybe I should start to look for something else for OSX)
------I attached the messages shown in "terminal" below-----------------
(openmodal-virtualenv) mitsuhashi-kousaku-no-iMac-2:OpenModal kousakumitsuhashi$ python openmodal.py
Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).
Welcome update time: 1.9073486328125e-06 seconds
GVA info: Successfully connected to the Intel plugin, offline Gen9 
Clearing previous models
Storing model id: 0
Geometry update time: 0.016124963760375977 seconds
Exc type changed
Measurement update time: 0.010368108749389648 seconds
Identification update time: 0.024173736572265625 seconds
Clearing previous models
Storing model id: 0
2D data not available.
Animation update time: 0.02921605110168457 seconds
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
model 0.000000 already stored - skipping
QLayout: Attempting to add QLayout "" to dialog_geom_primitives "", which already has a layout
QWidget::setLayout: Attempting to set QLayout "" on dialog_geom_primitives "", which already has a layout
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "../OpenModal/gui/widgets/geometry.py", line 921, in create_geom_primitive
    self.create_line_geom(input_data)
  File "../OpenModal/gui/widgets/geometry.py", line 965, in create_line_geom
    node_mask=self.modaldata.tables['geometry'].ix[:,'node_nums'].isin(node_nums)
  File "/Users/kousakumitsuhashi/Desktop/OpenModal/OpenModal/openmodal-virtualenv/lib/python3.6/site-packages/pandas/core/series.py", line 2555, in isin
    result = algorithms.isin(_values_from_object(self), values)
  File "/Users/kousakumitsuhashi/Desktop/OpenModal/OpenModal/openmodal-virtualenv/lib/python3.6/site-packages/pandas/core/algorithms.py", line 426, in isin
    return f(comps, values)
  File "/Users/kousakumitsuhashi/Desktop/OpenModal/OpenModal/openmodal-virtualenv/lib/python3.6/site-packages/pandas/core/algorithms.py", line 404, in <lambda>
    f = lambda x, y: htable.ismember_object(x, values)
  File "pandas/_libs/hashtable_func_helper.pxi", line 428, in pandas._libs.hashtable.ismember_object (pandas/_libs/hashtable.c:30162)
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'double'
Abort trap: 6
