### ISSUE TITLE
Does not import uff

### ISSUE THREAD

**Issue by ignvinay** [openmodal/OpenModal#48]
Trying this on windows10. Resolved all setup related issues. Now able to bring up the UI.
when i try importing .uff , it gives error:

uff_parse) D:\openmodal\OpenModal>python OpenModal\openmodal.py
Welcome update time: 0.0 seconds
Clearing previous models
Storing model id: 0
Geometry update time: 0.03390932083129883 seconds
Exc type changed
Measurement update time: 0.01595783233642578 seconds
Identification update time: 0.04587721824645996 seconds
Clearing previous models
Storing model id: 0
2D data not available.
Animation update time: 0.055850982666015625 seconds
Warning: There is no INFO or UNITS field!
Traceback (most recent call last):
  File "D:\openmodal\OpenModal\OpenModal\gui\skeleton.py", line 968, in run
    self.modaldata_object.import_uff(self.file_name)
  File "D:\openmodal\OpenModal\OpenModal\modaldata.py", line 386, in import_uff
    uffdata = ModalDataUff(fname, base_key=base_key)
  File "D:\openmodal\OpenModal\OpenModal\modaldata.py", line 644, in __init__
    self.create_model()
  File "D:\openmodal\OpenModal\OpenModal\modaldata.py", line 673, in create_model
    self.populate_model(model_id+self.base_key, model)
  File "D:\openmodal\OpenModal\OpenModal\modaldata.py", line 683, in populate_model
    self.gen_measurement_table(model_id, model)
  File "D:\openmodal\OpenModal\OpenModal\modaldata.py", line 696, in gen_measurement_table
    mnums += model[0]
IndexError: list index out of range

**Comment by pmg3275** [comment]
Hello Vinay, I am new to coding and python. I tried to instal the OpenModal package on my windows machine but didnt succeed. Could you share the step by step procedure or share how did it. you could write to me on pmg3275@gmail.com. sorry for spamming, your help is appriciated.
I have installed python and when i tried to follow the steps to install this package, it says I miss some modules. like PyQt5 etc

![image](https://user-images.githubusercontent.com/63732849/79487890-8ec3b000-8036-11ea-9599-bd0477e3e988.png)

**Comment by pmg3275** [comment]
> PyQt5
I could launch the openmodal.py and also bring up the UI.
But the GUI closes when i try importing .uff and in pthon terminnal i get below error:

![image](https://user-images.githubusercontent.com/63732849/79608314-6610e880-8112-11ea-85fd-53b13b9e3051.png)
