### ISSUE TITLE
Error in animation.py

### ISSUE THREAD

**Issue by gusshmn** [openmodal/OpenModal#56]
Hello all,
after successfully launching the OM.exe I would like to get it as well running by code. So I can understand the functionality and maybe edit or even build on top of it.

After making a fork of the repository and pip installing some additional requirements (pyqt-graph, OpenGL, PyDAQmx and pyuff) I did get an error 
`name 'ctypes' is not defined` 
I figured I could ad 
`import ctypes` to the DAQTask.py

Now I'm getting another error I can't tell if is my environment (using Python 3.8.3 via Spyder 4.1.5 Anaconda) or some other problem.

Thanks for your help in advance.

```
runfile('../GitHub/OpenModal/OpenModal/openmodal.py', wdir='../GitHub/OpenModal/OpenModal')
Welcome update time: 0.0 seconds
Clearing previous models
Storing model id: 0
Traceback (most recent call last):

  File "..\GitHub\OpenModal\OpenModal\openmodal.py", line 64, in <module>
    main_window = sk.FramelesContainer(app.desktop())

  File "..\GitHub\OpenModal\OpenModal\gui\skeleton.py", line 301, in __init__
    self.main_app = MainApp(desktop_widget, self.frameGeometry, self)

  File "..\GitHub\OpenModal\OpenModal\gui\skeleton.py", line 376, in __init__
    self.main_window = MainWindow(desktop_widget, frameGeometry, main_window_handle)

  File "..\GitHub\OpenModal\OpenModal\gui\skeleton.py", line 655, in __init__
    self._load_all_widgets()

  File "..\GitHub\OpenModal\OpenModal\gui\skeleton.py", line 725, in _load_all_widgets
    self.open_stack[key].reload()

  File "..\OpenModal\gui\widgets\geometry.py", line 2170, in reload
    self.build_uff_tree(self.modaldata,refresh=refresh)

  File "..\OpenModal\gui\widgets\geometry.py", line 1957, in build_uff_tree
    self.models[model_id] = Model(model_id, model_name, modal_data, None, self.model_view,

  File "..\OpenModal\gui\widgets\animation.py", line 1054, in __init__
    self.set_node_color(self.def_node_color)

  File "..\OpenModal\gui\widgets\animation.py", line 1075, in set_node_color
    self.modal_data.tables['geometry'].ix[model_mask,'clr_r']=rgba_color[0]/ 255.  # rbg values 0-1

  File "..\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5139, in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'ix'


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "..\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "..\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
ModuleNotFoundError: No module named 'daqprocess'
```

**Comment by jankoslavic** [comment]
For name 'ctypes' is not defined:
my guess is that when you installed NI-DAQmx drivers you did not install the C API!

**Comment by gusshmn** [comment]
Thank you for your answer. I did reinstall the driver for NI-DAQmx including the support for C. But the same error came up. Maybe I did something wrong setting up my environment. I will check on that today.
